---
apiVersion: v1
kind: Service
metadata:
  name: weechaw-ssh
  labels:
    k8s.labs.ahinh.me/prometheus-component: ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: weechaw.k8s.labs.ahinh.me
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: weechaw
  ports:
    - name: ssh
      port: 22
      targetPort: 22
