apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ext-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: ceph-csi-rbd
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: external-secrets-opassword
    kind: ClusterSecretStore
  target:
    name: csi-rbd-secret
  dataFrom:
  - extract:
      key: ceph-csi