apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
    app: test
spec:
  containers:
  - name: test
    image: crccheck/hello-world
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
  labels:
    name: test
    app: test
spec:
  selector:
    app: test
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000