apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: longhorn
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'longhorn-{{cluster}}'
      labels:
        app: longhorn
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: longhorn
        helm:
          valueFiles:
            - values.yaml
          releaseName: longhorn
      destination:
        server: '{{url}}'
        namespace: longhorn-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: longhorn