apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # decryption of tls occurs in the backend service
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/tls-acme: "false"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - longhorn.platform.labs.ahinh.me
      secretName: longhorn-cert-tls
  ingressClassName: nginx
  rules:
    - host: longhorn.platform.labs.ahinh.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80