longhorn:
  service:
    ui:
      type: LoadBalancer
  httproute:
    enabled: true
    hostname: longhorn.k8s.labs.ahinh.me
    parentRefs:
      gatewayName: k8s-labs
      sectionName: http
      namespace: nginx-gateway
    pathType: PathPrefix
    path: /

  defaultSettings:
    createDefaultDiskLabeledNodes: true

  helmPreUpgradeCheckerJob:
    enabled: false # Breaks ArgoCD