apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: debian-12-volume-template
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'debian-12-volume-template-{{cluster}}'
      labels:
        app: debian-12-volume-template
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: kubevirt/vms/template/debian-12
      destination:
        server: '{{url}}'
        namespace: kubevirt-vms
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: debian-12-volume-template