loki:
  tableManager:
    retention_period: "168h" # 1 week
    retention_deletes_enabled: true
  loki:
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    auth_enabled: false
  singleBinary:
    replicas: 1