apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: backstage
          image: gcr.io/ahinh-homelab/backstage:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: POSTGRES_SERVICE_HOST
              value: backstage-postgresql.backstage.svc.cluster.local
            - name: POSTGRES_SERVICE_PORT
              value: "5432"
            - name: PGSSLMODE
              value: "require"
          envFrom:
            - secretRef:
                name: github-token
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets