apiVersion: v1
kind: Service
metadata:
  name: backstage-nginx
  namespace: backstage
spec:
  selector:
    app: backstage-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: api
      port: 7007
      targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: api
      port: 7007
      targetPort: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      hostname: backstage
      subdomain: pod
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: backstage
          image: gcr.io/ahinh-homelab/backstage:v1.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: backstage-http
              containerPort: 7007
          env:
            - name: POSTGRES_SERVICE_HOST
              value: backstage-postgresql-03.backstage.svc.cluster.local
            - name: POSTGRES_SERVICE_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres.backstage-postgresql-03.credentials.postgresql.acid.zalan.do
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.backstage-postgresql-03.credentials.postgresql.acid.zalan.do
                  key: password
                  optional: false
            - name: PGSSLMODE
              value: "require"
          envFrom:
            - secretRef:
                name: github-token
            - secretRef:
                name: backstage-secrets
          volumeMounts:
            - name: postgres-ca-cert
              mountPath: "/var/ssl/ca"
              readOnly: true
      volumes:
        - name: postgres-ca-cert
          secret:
            secretName: postgres-ca
            optional: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-nginx
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-nginx
  template:
    metadata:
      labels:
        app: backstage-nginx
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: nginx
          image: gcr.io/ahinh-homelab/backstage-nginx:v1.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: api
              containerPort: 7007
          volumeMounts:
            - name: nginx-tls-cert
              mountPath: "/var/ssl/tls"
              readOnly: true
            - name: nginx-tls-dhparams-cert
              mountPath: "/var/ssl/dhparams"
              readOnly: true
      volumes:
        - name: nginx-tls-cert
          secret:
            secretName: backstage-nginx-tls
            optional: false
        - name: nginx-tls-dhparams-cert
          secret:
            secretName: backstage-nginx-tls-dhparam
            optional: false