apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: registry
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
            k8s.labs.ahinh.me/region: us-central
  template:
    metadata:
      name: "registry-{{name}}"
      labels:
        app: registry
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: registry/base
      destination:
        name: "{{name}}"
        namespace: registry
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: registry
