apiVersion: v1
kind: Service
metadata:
  name: terraria-1
  labels:
    k8s.labs.ahinh.me/prometheus-component: app
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: terraria-1
  ports:
    - name: terraria
      port: 7777
      targetPort: 7777
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: terraria-1-ssh
  labels:
    k8s.labs.ahinh.me/prometheus-component: ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: terraria-1.k8s.labs.ahinh.me
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: terraria-1
  ports:
    - name: ssh
      port: 22
      targetPort: 22
