apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: default
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /data
        name: test
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: test
  restartPolicy: Always