apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: external-secrets-vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret
  data:
  - secretKey: foobar
    remoteRef:
      key: labs/woohoo