apiVersion: v1
kind: Service
metadata:
  name: minecraft-1
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: minecraft-1
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
  - name: minecraft-udp
    port: 25565
    targetPort: 25565
    protocol: UDP