apiVersion: v1
kind: Service
metadata:
  name: minecraft-1
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: minecraft-1
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: minecraft-udp
      port: 25565
      targetPort: 25565
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-1-ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft-1.k8s.labs.ahinh.me
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: minecraft-1
  ports:
    - name: ssh
      port: 22
      targetPort: 22
