apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
  template:
    metadata:
      name: "istio-base-{{cluster}}"
      labels:
        app: istio-base
    spec:
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.failurePolicy
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: istio/base
        helm:
          valueFiles:
            - values.yaml
          releaseName: istio-base
      destination:
        name: "{{name}}"
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
        managedNamespaceMetadata:
          labels:
            app: istio-base
