apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres.{{ .Release.Name }}-postgresql.credentials.postgresql.acid.zalan.do
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: external-secrets-vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres.{{ .Release.Name }}-postgresql.credentials.postgresql.acid.zalan.do
  data:
  - secretKey: username
    remoteRef:
      key: secret/harbor/postgresql/credentials
      property: primary.username
  - secretKey: password
    remoteRef:
      key: secret/harbor/postgresql/credentials
      property: primary.password