apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ext-secret
  namespace: {{ .Release.Namespace | quote }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: external-secrets-vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-ext-secret
  data:
  - secretKey: argocd-ext-secret
    remoteRef:
      key: secret/argocd/secrets