apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ext-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: external-secrets-opassword
    kind: ClusterSecretStore
  target:
    name: argocd-ext-secret
  dataFrom:
  - extract:
      key: argocd