apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appsets-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: localhost
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "argocd-appsets-services"
      labels:
        app: argocd-appsets-services
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: argocd-appsets/services
      destination:
        server: "{{url}}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
