apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ceph-csi-rbd
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
  template:
    metadata:
      name: "ceph-csi-rbd-{{name}}"
      labels:
        app: ceph-csi-rbd
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: ceph-csi
      destination:
        name: "{{name}}"
        namespace: ceph-csi-rbd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: ceph-csi-rbd
