apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudnativepg
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
  template:
    metadata:
      name: "cloudnativepg-{{name}}"
      labels:
        app: cloudnativepg
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: cloudnativepg
        helm:
          valueFiles:
            - values.yaml
          releaseName: cloudnativepg
      destination:
        name: "{{name}}"
        namespace: cloudnativepg
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            app: cloudnativepg
