apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
    # Explicit kube1 declaration because it uses a mislabeled auth backend in Vault. Whoops!
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
            k8s.labs.ahinh.me/cluster-name: kube1
        values:
          mountPath: "kubernetes"
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
        values:
          mountPath: "{{name}}"
  template:
    metadata:
      name: "external-secrets-{{name}}"
      labels:
        app: external-secrets
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: external-secrets
        helm:
          valueFiles:
            - values.yaml
          valuesObject:
            externalsecrets:
              secretStore:
                enabled: true
                mountPath: "{{ values.mountPath }}"
                role: external-secrets
          releaseName: external-secrets
      destination:
        name: "{{name}}"
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: external-secrets
