apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
        values:
          name: "{{name}}"
          region: "{{metadata.labels.k8s.labs.ahinh.me/region}}"
          role: "{{metadata.labels.keycloak.k8s.labs.ahinh.me/db-role}}"
  template:
    metadata:
      name: keycloak-{{values.name}}
      labels:
        app: keycloak
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-service-keycloak.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
            - "{{values.role}}/values.yaml"
          releaseName: keycloak
      destination:
        name: "{{values.name}}"
        namespace: keycloak
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: keycloak
