apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchLabels:
      bgp-policy: kube2
  virtualRouters: # []CiliumBGPVirtualRouter
    - localASN: 64551
      exportPodCIDR: true
      neighbors: # []CiliumBGPNeighbor
        - peerAddress: "10.1.1.1/32"
          peerASN: 64512
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 20
          advertisedPathAttributes:
            - selectorType: CiliumLoadBalancerIPPool
              selector:
                matchLabels:
                  cluster: kube2
              communities:
                standard:
                  - 65001:100 # Must be unique within the network!
            - selectorType: PodCIDR
              localPreference: 135
              communities:
                standard:
                  - 65001:150 # Must be unique within the network!
      serviceSelector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
