apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
  template:
    metadata:
      name: "nginx-gateway-fabric-{{cluster}}"
      labels:
        app: nginx-gateway-fabric
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: nginx-gateway-fabric
      destination:
        name: "{{name}}"
        namespace: nginx-gateway
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: nginx-gateway-fabric
