apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
      - cluster: kube2
        url: https://kube2.labs.ahinh.me:6443
  template:
    metadata:
      name: 'nginx-gateway-fabric-{{cluster}}'
      labels:
        app: nginx-gateway-fabric
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: nginx-gateway-fabric
      destination:
        server: '{{url}}'
        namespace: nginx-gateway
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: nginx-gateway-fabric