apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
  template:
    metadata:
      name: "ingress-nginx-{{cluster}}"
      labels:
        app: ingress-nginx
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: nginx-ingress
        helm:
          valueFiles:
            - values.yaml
            - "{{cluster}}/values.yaml"
          releaseName: ingress-nginx
      destination:
        name: "{{name}}"
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: ingress-nginx
