apiVersion: v2
name: ingress-nginx
version: 1.0.0
description: ingress-nginx helm chart
type: application
home: https://k8s.labs.ahinh.me
sources:
  - https://github.com/ahinh43/homelab-k8s-config
dependencies:
  - name: ingress-nginx
    version: 4.11.2
    repository: https://kubernetes.github.io/ingress-nginx