apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: platform.adahinh.net
      http:
        paths:
          - path: /demo
            pathType: Prefix
            backend:
              service:
                name: httpd-service
                port:
                  number: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  containers:
  - name: httpd
    image: httpd:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: httpd-service
spec:
   selector:
      app: httpd
   type: NodePort
   ports:
      - name: main
        protocol: TCP
        port: 8080
        targetPort: 80