ingress-nginx:
  controller:
    admissionWebhooks:
      patch:
        podAnnotations:
          sidecar.istio.io/inject: "false"
    replicaCount: 3
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: controller
        topologyKey: node-role.kubernetes.io/worker
        maxSkew: 1
        whenUnsatisfiable: ScheduleAnyway
  annotations:
    traffic.sidecar.istio.io/includeInboundPorts: ""
    traffic.sidecar.istio.io/excludeInboundPorts: "80,443"
    # traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.96.0.0/16,10.246.0.0/16"
    sidecar.istio.io/inject: 'true'