apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weechaw
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: kube1
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "weechaw-{{cluster}}"
      labels:
        app: weechaw
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: kubevirt/vms/overlays/weechaw
      destination:
        server: "{{url}}"
        namespace: kubevirt-vms
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
