# Source: vault/charts/vault/templates/server-ingress.yaml
# Hacky way to get clustermesh going
{{ if .Values.ciliumService.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: vault.k8s.labs.ahinh.me
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  tls:
    - hosts:
        - "vault.k8s.labs.ahinh.me"
        - "vault.local.k8s.labs.ahinh.me"
      secretName: vault-cert-tls
  ingressClassName: nginx
  rules:
    - host: "vault.k8s.labs.ahinh.me"
      http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-active
                port:
                  number: 8200
    - host: "vault.local.k8s.labs.ahinh.me"
      http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-active
                port:
                  number: 8200
{{ end }}