apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
      - cluster: kube2
        url: https://kube2.labs.ahinh.me:6443
  template:
    metadata:
      name: 'istiod-{{cluster}}'
      labels:
        app: istiod
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: istio/istiod
        helm:
          valueFiles:
            - values.yaml
          releaseName: istiod
      destination:
        server: '{{url}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: istiod