ingress-nginx:
  controller:
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: controller
        topologyKey: kubernetes.io/hostname
        maxSkew: 2
        whenUnsatisfiable: ScheduleAnyway