apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: debian-12-vm-template
spec:
  running: true
  template:
    spec:
      evictionStrategy: LiveMigrate
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk0
            - disk:
                bus: virtio
              name: cloudinitdisk
        resources:
          requests:
            cpu: "4"
            memory: 17408M
      volumes:
        - dataVolume:
            name: asa-ds-1
          name: disk0
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: asa-ds-1-cloudinit-userdata
            networkDataSecretRef:
              name: asa-ds-1-cloudinit-networkdata
