apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testvm-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - name: testpvc
              lun: {}
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - containerDisk:
            image: ubuntu:22.04
          name: containerdisk
        - name: testpvc
          persistentVolumeClaim:
            claimName: testvm-pvc