apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: fedora2
  name: fedora2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora2
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: disk0
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 2048M
      volumes:
      - dataVolume:
          name: fedora2-dv
        name: disk0
      - cloudInitNoCloud:
          userData: |
            #cloud-config 
            user: fedora 
            password: bananas
            hostname: fedora2.kubevirt-vms.svc.cluster.local
            ssh_pwauth: True 
            disable_root: false
        name: cloudinitdisk
      networks:
        - name: default
          pod: {}
  dataVolumeTemplates:
  - metadata:
      name: fedora2-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
      source:
        http:
          url: https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.raw.xz