apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
      - cluster: kube2
        url: https://kube2.labs.ahinh.me:6443
  template:
    metadata:
      name: keycloak-{{cluster}}
      labels:
        app: keycloak
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: keycloak
        helm:
          valueFiles:
            - values.yaml
            - '{{cluster}}/values.yaml'
          releaseName: keycloak
      destination:
        server: '{{url}}'
        namespace: keycloak
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: keycloak