{{ if .Values.externalsecrets.secretstore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-vault-backend
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: "https://vault.local.k8s.labs.ahinh.me"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.externalsecrets.secretstore.mountPath }}
          role: {{ .Values.externalsecrets.secretstore.role }}
          serviceAccountRef:
            name: {{ .Values.externalsecrets.serviceAccount.name }}
            namespace: {{ .Release.Namespace }}
{{ end }}