apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          name: "{{name}}"
          region: "{{metadata.labels.k8s.labs.ahinh.me/region}}"
  template:
    metadata:
      name: "sealed-secrets-{{values.name}}"
      labels:
        app: sealed-secrets
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: sealed-secrets
        helm:
          valueFiles:
            - values.yaml
            - "{{values.region}}/values.yaml"
          releaseName: sealed-secrets
      destination:
        server: "{{values.name}}"
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: sealed-secrets
