apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubevirt-fedora-39-image
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'kubevirt-fedora-39-image-{{cluster}}'
      labels:
        app: kubevirt-fedora-39-image
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: kubevirt/images/fedora/39
      destination:
        server: '{{url}}'
        namespace: kubevirt
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: kubevirt-fedora-39-image