apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:
  WAL_S3_BUCKET: ahinh-postgres-magical-backups
  WAL_BUCKET_SCOPE_PREFIX: ""
  WAL_BUCKET_SCOPE_SUFFIX: ""
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: '00 12 * * *'
  AWS_ACCESS_KEY_ID: replaceme
  AWS_SECRET_ACCESS_KEY: replaceme
  AWS_ENDPOINT: https://s3.us-west-2.amazonaws.com:443 # Endpoint URL to your S3 Endpoint; MinIO in this example
  AWS_REGION: us-west-2
  BACKUP_NUM_TO_RETAIN: "5"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_AWS_ACCESS_KEY_ID: replaceme
  CLONE_AWS_SECRET_ACCESS_KEY: replaceme
  CLONE_AWS_ENDPOINT: https://s3.us-west-2.amazonaws.com:443 # Endpoint URL to your S3 Endpoint; MinIO in this example
  CLONE_AWS_REGION: us-west-2
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_WAL_BUCKET_SCOPE_PREFIX: ""
  CLONE_WAL_S3_BUCKET: ahinh-postgres-magical-backups
  CLONE_AWS_S3_FORCE_PATH_STYLE: "true"