apiVersion: v1
kind: Service
metadata:
  name: cap10mc
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: cap10mc
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: minecraft-udp
      port: 25565
      targetPort: 25565
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: cap10mc-ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cap10mc.k8s.labs.ahinh.me
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: cap10mc
  ports:
    - name: ssh
      port: 22
      targetPort: 22
