argo-cd:
  global:
    domain: argo.k8s.labs.ahinh.me
  server:
    replicas: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        external-dns.alpha.kubernetes.io/hostname: argo.k8s.labs.ahinh.me
      extraHosts:
        - name: argo.k8s.labs.ahinh.me
          path: /
        - name: argo.local.k8s.labs.ahinh.me
          path: /
      extraTls:
        - hosts:
            - argo.k8s.labs.ahinh.me
            - argo.local.k8s.labs.ahinh.me
          secretName: argocd-cert-tls
  repoServer:
    replicas: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
  controller:
    replicas: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
  configs:
    params:
      server.insecure: true
    cm:
      create: true
      url: https://argo.k8s.labs.ahinh.me
      oidc.config: |
        name: Keycloak
        issuer: http://keycloak.k8s.labs.ahinh.me/realms/labs
        clientID: $argocd-ext-secret:keycloak.oidc.clientID
        clientSecret: $argocd-ext-secret:keycloak.oidc.clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups
    rbac:
      create: true
      policy.default: ""
      policy.csv: |
        g, argocd-admin, role:admin
