# argo-cd:
#   server:
#     ingress:
#       https: true
#       enabled: true
#       ingressClassName: nginx
#       hosts:
#         - argo.platform.labs.ahinh.me
#       annotations:
#         cert-manager.io/cluster-issuer: "letsencrypt"
#         nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#       tls:
#         - hosts:
#             - argo.platform.labs.ahinh.me
#           secretName: argocd-cert-tls