apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  labels:
    alertmanagerConfig: discord
spec:
  route:
    groupBy: ['namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
    routes:
      - match:
          severity: "critical"
        receiver: discord
  receivers:
  - name: 'discord'
    discordConfigs:
      - apiURL:
          key: DISCORD_WEBHOOK_URL
          name: alertmanager-ext-secret
          optional: false