apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  labels:
    alertmanagerConfig: discord
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
  receivers:
  - name: 'discord'
    discordConfigs:
      - webhook_url_file: "/etc/alertmanager/secrets/alertmanager-ext-secret/DISCORD_WEBHOOK_URL"
    