apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  labels:
    alertmanagerConfig: discord
spec:
  route:
    groupBy: ['alertname', 'namespace', 'job', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord'
    matchers:
      - name: severity
        value: "critical"
        matchType: "="
  receivers:
  - name: 'discord'
    discordConfigs:
      - apiURL:
          key: DISCORD_WEBHOOK_URL
          name: alertmanager-ext-secret
          optional: false