apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTPS
    port: 443
    name: https
    hostname: "*.k8s.labs.ahinh.me"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: cilium
  - protocol: HTTPS
    port: 443
    name: https-vault
    hostname: "vault.k8s.labs.ahinh.me"
    allowedRoutes:
      namespaces:
        from: vault
    tls:
      mode: Passthrough