apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            k8s.labs.ahinh.me/cluster-os: linux
        values:
          name: "{{name}}"
          region: "{{metadata.labels.k8s.labs.ahinh.me/region}}"
          role: "{{metadata.labels.vault.k8s.labs.ahinh.me/role}}"
  template:
    metadata:
      name: "vault-{{values.name}}"
      labels:
        app: vault
    spec:
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: vault
        helm:
          valueFiles:
            - values.yaml
            - "{{values.role}}/values.yaml"
          releaseName: vault
      destination:
        name: "{{values.name}}"
        namespace: vault
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: vault
