vault:
  server:
    service:
      active:
        annotations:
          service.cilium.io/global: "true"
    ha:
      enabled: true
      raft:
        enabled: true
  ui:
    enabled: true
    serviceType: LoadBalancer