vault:
  server:
    service:
      active:
        annotations:
          service.cilium.io/global: "true"
    ha:
      enabled: false
      raft:
        enabled: true
    
    dataStorage:
      enabled: true
      storageClass: longhorn
  ui:
    enabled: true
    serviceType: LoadBalancer
    httproute:
      enabled: true
      hostname: vault.k8s.labs.ahinh.me
      parentRefs:
        gatewayName: k8s-labs
        sectionName: https
        namespace: nginx-gateway
      pathType: PathPrefix
      path: /