apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "debian-12-vm-dv"
spec:
  source:
      pvc:
        name: debian-12-template
        namespace: kubevirt-vms
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "4Gi"