
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: debian-12-vm-template
    k8s.labs.ahinh.me/app: debian-12-vm-template
    k8s.labs.ahinh.me/component: vm
    k8s.labs.ahinh.me/os: linux
    k8s.labs.ahinh.me/distro: debian
    k8s.labs.ahinh.me/version: "12"
  name: debian-12-vm-template
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: disk0
        resources:
          requests:
            memory: 2048M
      networks:
        - name: default
          pod: {}
      volumes:
      - dataVolume:
          name: debian-12-vm-template-dv
        name: disk0