apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flatcar-linux-update-operator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - policy
    resourceNames:
      - flatcar-linux-update-operator
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flatcar-linux-update-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - policy
    resourceNames:
      - flatcar-linux-update-agent
    resources:
      - podsecuritypolicies
    verbs:
      - use
