# Prometheus scrape config
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: palworld-1
  namespace: kubevirt-vms
  labels:
    prometheus: system-monitoring-prometheus
    kubevirt.io/vm: palworld-1
    k8s.labs.ahinh.me/app: palworld-1
    k8s.labs.ahinh.me/component: vm
    k8s.labs.ahinh.me/os: linux
    k8s.labs.ahinh.me/distro: debian
    k8s.labs.ahinh.me/version: "12"
    k8s.labs.ahinh.me/backup-schedule: main
spec:
  staticConfigs:
    - labels:
        host: palworld-1
      targets:
        - palworld-1.kubevirt-vms.svc.cluster.local:9100
