apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: palworld-1
  namespace: kubevirt-vms
  labels:
    prometheus: system-monitoring-prometheus
    kubevirt.io/vm: palworld-1
    k8s.labs.ahinh.me/app: palworld-1
    k8s.labs.ahinh.me/component: vm
    k8s.labs.ahinh.me/os: linux
    k8s.labs.ahinh.me/distro: debian
    k8s.labs.ahinh.me/version: "12"
    k8s.labs.ahinh.me/backup-schedule: main
    release: kube-prometheus-stack
spec:
  endpoints:
    - bearerTokenSecret:
        key: ""
      port: prometheus
      scheme: http
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - kubevirt-vms
  selector:
    matchLabels:
      k8s.labs.ahinh.me/prometheus-component: "app"
