apiVersion: v1
kind: Service
metadata:
  name: palworld-1
  labels:
    k8s.labs.ahinh.me/prometheus-component: app
spec:
  type: LoadBalancer
  selector:
    k8s.labs.ahinh.me/component: app
    kubevirt.io/vm: palworld-1
  ports:
    - name: palworld
      port: 8211
      targetPort: 8211
      protocol: UDP
    - name: query
      port: 27015
      targetPort: 27015
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
    - name: rcon-udp
      port: 25575
      targetPort: 25575
      protocol: UDP
    - name: prometheus
      port: 9100
      targetPort: 9100
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: palworld-1-ssh
  labels:
    k8s.labs.ahinh.me/prometheus-component: ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: palworld-1.k8s.labs.ahinh.me
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: palworld-1
  ports:
    - name: ssh
      port: 22
      targetPort: 22
