apiVersion: v1
kind: Service
metadata:
  name: palworld-1
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: palworld-1
  ports:
    - name: palworld
      port: 8211
      targetPort: 8211
      protocol: UDP
    - name: rcon
      port: 27020
      targetPort: 27020
      protocol: TCP
    - name: rcon-udp
      port: 27020
      targetPort: 27020
      protocol: UDP
    - name: prometheus
      port: 9100
      targetPort: 9100
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: palworld-1-ssh
  annotations:
    external-dns.alpha.kubernetes.io/hostname: palworld-1.k8s.labs.ahinh.me
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: palworld-1
  ports:
    - name: ssh
      port: 22
      targetPort: 22
