keycloak:
  externalDatabase:
    host: keycloak-postgresql.keycloak.svc.cluster.local
    existingSecret: postgres.keycloak-postgresql.credentials.postgresql.acid.zalan.do
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: keycloak.k8s.labs.ahinh.me
      external-dns.alpha.kubernetes.io/parent: keycloak/keycloak

postgresOperator:
  createDatabase: false
  createService: true