prometheus:
  prometheus:
    agentMode: true
    prometheusSpec:
      remoteWrite:
        - url: http://{{ .Release.Name }}-prometheus.{{ .Release.Namespace }}:9090/api/v1/write
      externalLabels:
        cluster: kube2
    service:
      annotations:
        service.cilium.io/affinity: remote
  thanosIngress:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false