prometheus:
  prometheus:
    agentMode: true
    prometheusSpec:
      remoteWrite:
        - url: http://{{ .Release.Name }}-prometheus.{{ .Release.Namespace }}/push
      externalLabels:
        cluster: kube2
  thanosIngress:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false