prometheus:
  prometheus:
    agentMode: true
    prometheusSpec:
      remoteWrite:
        - url: http://{{ .Release.Name }}-prometheus.{{ .Release.Namespace }}/push
      replicas: 0
  thanosIngress:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false