keycloak:
  externalDatabase:
    host: keycloak-postgresql.keycloak.svc.cluster.local
    existingSecret: postgres.keycloak-postgresql.credentials.postgresql.acid.zalan.do
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: keycloak.k8s.labs.ahinh.me
      external-dns.alpha.kubernetes.io/parent: keycloak/keycloak
  # Only create the service w/ the Cilium clustermesh, do not create any replicas
  # The data is sadly not 1:1 replicated from the primary cluster to secondaries
  # so it causes session caching/cookie issues
  replicaCount: 0

postgresOperator:
  createDatabase: false
  createService: true
