apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ceph-csi-rbd
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: kube1
        url: https://kubernetes.default.svc
      - cluster: kube2
        url: https://kube2.labs.ahinh.me:6443
  template:
    metadata:
      name: 'ceph-csi-rbd-{{cluster}}'
      labels:
        app: ceph-csi-rbd
    spec:
      project: default
      source:
        repoURL: git@github.com:ahinh43/homelab-k8s-config.git
        targetRevision: HEAD
        path: ceph-csi
      destination:
        server: '{{url}}'
        namespace: ceph-csi-rbd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app: ceph-csi-rbd