---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgBsOz8MqSQ3vLDjxF7nfZcBqmydE/9SX56l3EWhR5LTYlrhUOgBL6hMDqHYdMw2jjhEkZ1sFuHFsqrAt7dAwMs62uohGR5wYrC8QHpM5yZA8HPBLMpcl9QOfL2eUEsKWD565pIpPRNpt71B/5fB/D+b1NlLiR3HfeWKOJAzJUP055kN32Op2TomTujiDp/41CLgBBLXOhHaeJINr256yO7Pjgfvhpky9MVguEk+cQDpAVOIaxwTUVGU0q3u80vjzltvyjiwPsDZm0uuGmY3p6vEXJZ8U55ypf31f+wD5Jnr8hdEMKLcLaqZW8tKDMR05aD39Rofe9pDA6Ys13CZmVZPE2nvlyaQsG7mZcFc2UGu4rQPupXVpcFeML26mm7fGci4yhnwZ8xOSAVPZhmbK4y6m5dKEHE2Cv3L3VfjeomKDscZftG1DZbpWlwJBeK2/4tcUaCwrEdCFeKnxUapP638Mjz309ljGcF9frh199mUZUh4GFvtAb1EzqI6vClzOFjAwZ/aOexGNyxnQwpKmBrl5xPJFDPvi1UJw2VfEGTkPSlhAJ/cNNv6iFOBxCiwstCoaAfEgPvhxPUnmvHxIrp6nSRpQ19cQWh1e5lB+aPXz2lvYq0YCQoDrGoYMHS67fc92yNjHuo1kjsf/KukFunoGFpGGyuUa+tsjMinKYMiJoZVFfcqx9Zy779PEC55JV0nAtabXFX/o2TS
    userKey: AgCV5dX+G8I9nkL6zI7KzuZESfgTuwgo1Yy2mKGhu/88sk9oNG+E5LB62pE7IUxQ5xjY9KDaVDtIF+E+qaj/AM34w1G9RSYY+H5nuSvS7Yc46iABGugaxP1Fxz1g6/ObK6yKdnNOZtKGvzvmUOBMbptO7KxiKvPj0+VZoQvOxXEstzkx/miP2Aqnw5sSx0AWFocIdWbr5fC819N014LIguoF+EPscry1akkl3VA0izOLirWTTzApc7x7oVcblycNZcNTymFtgdAl2jh0e0Y/6xF1MFwmE+t2ua9DJ521904mq1gorxiu/G1zRPKOTmvYUsi/yFwTV//ohpmhtNRkmDUVeheIfERfz8NbnkoS8KRs1Dhk4dDJ9FMzKQJnEHNnu8pKNdONHsdU2YBJvJTBH6OaIenZO/2t2vz9AOn6tGnVepa/AL7avmINwBqdqd2pWAhqkJfC4pILG9HJG5u1BeLvEh81LYB8d0Ksuzc+6gAoMCOMX7zhY9ObwAjWeVwnNQfgRqIeDmNPr1fHa0PCSwa4dsDGaY38GQZ0//3WVcoalmfZggvctZCwwcqL469UM13Qo9ic4Qml8564Kx8d3JaJBAlhOlH2gjJd+zClI6O7jVORP8hyzwJS7zxeSwko00HZjL4OK6Bq2NY9SMIkc0g2MWxnqh4OCeH9+OYzUp/zjbIYb6H57+7jrGvFopGafv1EZ5+OM9ypO5C4XjYnPbDe0JB76yDqLfckKW1Ni5zaq66t3/FG5GhA
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
