---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgAd/HL+usbREf0EypWfQT1Gvcg2ivsd5DvzyK8jLTzm2Rno8SQfX4vvpf+mBziKbxN52NBD9pXNrirkbLXddYJWYd6jxySoMmrQy5/E1PSTpxqA3X6WEkEvFjsjWv9qVl3UZPotGc+CQouMexw6UU0Tq58K7/Ot3Qcbv+M5LEIL1M4x5ZSUJze3p7rpy1wWNikik5h/LZdF/abvjJoQeDO1ZLVojaOYZctLoHWbhOGK6HHGkAFCUNI7py6FjmRgeg8X7CHiqOz6duE0+Q4HAHy9J7yqm+8wVzG0NN0O3Rco8iHlphJiYcTvMlcYiSSaJQOCdaRF3Ao99/QTLVe5/fo9ZVf7l5w4rcb+9AP18Yo3zt+T86HbrcFqS3wVLLtg8qiIRRwLANkqsN9IfrSZyOiiBNqraA3PpqiSyxQ/oBBl5z1n1iXkaD3zoD+/osDJT+cy8Ac6V0/Gs0eSsMiRUGyo6gwm89B72hPv2GAIK3/Ct7b7+DymynkRwGCLLyLoezCHynKbnEcyXnM4wYHZ4MFKSbr/GNdUEYPqhfdVuKxL5ookUlz7vW/Ox5CgGzxfitSa96HkYY/bX98O84iVrXCdBgOFu2Wc+UGwCefwvlvSbGUss6q/xS2wOOw7DF1+dlTy058zmPcKK0JuzGnbcDaCgYEO+Ta9HThJosPNfFG2ef4McekcPLtfA+oajAq8PsO1w0AbR4bfWAe+
    userKey: AgBWs0HjyBoIpTuZ/1DpZLLfD9tAKnp9o733ogTdy0x1SVSSf2eRcxFCz3M8JNI9DWT13kRN1x4RGW9Ns32VKMVQ3ScLj7LzaOP32xHgSofcCiF/OH0YA492yEtj7oSpTTBFGRsFoBaio+wdj33MwpZyw+hQ6ZCDoaFYIvfjwPFseBIVLfp50/bscgDJA1k0Y7jzsC2PB4qPpEnufuMq1Vu4FSVOZQXXvm2eVgrycjl1XI7/iVfU3o6Nj7gpU60fpsX0Anf9uxEVVYo9wSC7pwifHV1G8aH7UfuhEupY0wtMx1qqwWr19zRCde7BTjPJ2Lmzi5BzCyz+0F9bMzLkgi2VLZps37rHfeOTdxJqDinQ6G416om5sjSRe8g1S53vGhmJXiJz2VwtDlSgLp5mb3ilX/ICr/9ViT4wr2/99VCQsCPR+FSyOEd6vaKMIX0ZVs7Ms+C6qdaMQcjO9mf9d+SniHqbgYdzjeD184bdVhk4f9hmGjTEZTG96ByGHtb1Rc++5wIUSrxCnrS2sSQCvnn5wNKrwhD4/Za+Q0aKCCmQIoLNtGXXDE9LFz/ibK+i1OibHivdjbD+wK5Z2cPVqJm7wNyN7Mc0ciSBNL6/zPPR52MOD1utEic4Yup1DFQZZHVNWpSRtS35iCSaU4SMRKewDZu986oC53vB6w8h80P+XqRtZQ5ERvUAG/h0h0+D+PrDZtp8t42gZjMlxYH6P+ifTNMWlQvUiSXacRulrk21gkZrr61bX8WM
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
