---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgARwOZaa4BIp+edmeEUE/kixSsMvXX2x5YogLd+RzYTfVk7iWkpfk1JqJfC+aiNHL0zZbPAkjPGFWSQoPClfligLQxWQBJmcf0BVYX3C9fYlelg4Q8Q31MuvrAspGvKUYcUUWYQm7EDbNJtkhmOdARGEfckTwYS4RVa5WfW2ZfxgoGXgNIxZTSy5wFOZZhKX+nA1cBWY6FJ0mMT3XyDQuJdHidGbiN06GVFGPL1P67ILJCqYCV5itlaA1R2DZogx2KhJsKOBugpjyPVuAbqk7FgCHDNYZKmuLMfI46prc0omh/rLnc6prIHQmvICGDR1TG87lWgesb4aj3XZd6t6ewSt1KjYaiJIMGgj0QmudRGPA0FmYgxge3sIcFcG1z0kVjPf/5tA9kYrjvMjE7naxUzu3pWjQIaV7DJfoSYq2OTqYCSVWReRQXZBGopV6jEiUU0A5Q8p58rpdi2IpHjotDj2PyWvkg3z7TpG7GzrgcX+qASO7pxvBRasdkQf/CAH0jNkwdmCvSRvbMFRlvxYx+lkFoHT8eE8ZoZl6hsit627BUwFi9UkZm3QpIyMFOo3JIyXu1tPZzsihw9OAXlsK4I2f9oLypTwc7kGZ/G6JYYC2vi40GZlBt2W2SzdlO8jVjX12HmjyeCco4wkR7MclK3bTZv9uzmomHFj2fYyQKIvpeu30GHdPz17MKHjDa3jQHzeHgiMOKdmdjf
    userKey: AgCfd6IFduOvItp+5uuQjHbBBbygBRXpwWKSWD+AHLmNSpw1iimDf7OCawO3tnD7F9t5Q1G2PovZ9vmqI7Df9Luu9flqe39AjQfHp+s/9tYiqUzQYCy2UFYAEBCrlw/wKr/i2C5KHDZygUu+dGNrzkX0RrDG573OpPsoN7ZAbqOecBufD5XludY5i6nm5DstDDFyCFNvXQG+924GeUS+ECU0J8i7jYRhOddy2nlqBuRke5LLmLRDxkTmzVoHdBxwGcxLwGmbWPUpaQvrUManMzYMKi30gdDTmYy5yGiiulpJBSGlWt5TBQT3sGtCKeqtMAGJEnSJZEWhR7aSJTu4mRl3UdCmvH6CiZisD+MtsboRx5vaPr2yxI6cBv63qyEDJdGwJ6VK3T/yYwKcINbOsAwNNQC6RKNt6UYcNMsUqqzKivboNulwZKZcUbYzCptMeemyyzmvRFIXl7ss1KFf7BC51WwWNl2N1mCZheRdRNGeWPkzTWerY7KC6BruXaR3y+MynzkSmJOulaVomvgH6VSN/MpfRqpsD4FpOpJZUipnnVCV+mPlxTd2byaTvjHRxSa5D8/LuDcyvrG8hgdIyN3QjgCz5i0jOpgsld7dmDXd4Itp4e2/6LqAfOhGiGLIZt3uHa4OfZtiC8FSIlzKtcRfinPATWJfTYWL1+Gjip5+gn5bLQPzyOLXYYzaUXL1Zi2zEsqfYw9ERPKXBXZ4NG9U5Cto0uXzBXsNgES9rZHO3yLutJtEcpUC
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
