---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgA+XMHII84vzEA26wSXFSETD/iaA5m/seHACWuEAQPjiaIGUupHEloDqpxHKleDciaUfkkK1O3FftDfVVgeasa+bIhvcUp+PT2eKbbXXB5yYBQZJOacNAa4FU1rxrDiz3/gFyFkV4wiY3YoURBVn+agnhIS7gNb8lsx/GEJ0XLxxi8LUs6fRj3i/PVlAoVuG2Usq/O+l/9Kq12wfmEoD+6L9t0yRYIfctStNkfzaq8zaWeC66r529N/V5AtOuk0E5XzRgX5XpncA3srjsmD8FwriM554OUfbTBnAm6aKuHmvhyevi5qmBnDFzvBmYItuw4SRHYqImsBNcGprisV8JpjeNWHrzsjYps1+nxPLL8Z2EmyJSq56sdw2jJgWn6IiYl2+y191cXwxwMiPte5q87CSXfJKTHKYllX/z4VLku2Jn4cl08rz1cKYEI489s9BD1on+370qtJpn06TC/+BF5rNXOaabWPltAbzGu1llp1I5pTz1bvb0PqzeMDBkQMw6h7d8R42IgRXHAHTb+Kn8pdIr64zGwMipupY2QCa9wupjwLe2sJygHEJpeuCrwJQy+RXMNYfTr8JSWhx5pPsI0FvAWLWeEFbcCSntoQdzdmQr6+p6FgG4QleJlfjSRwvH/1JCsXPK1qIXlHHP0p30yu7zvUcrzPqxQBo1wQqfeT6+Ab0U0I8FsXP3qfc8v4/Z8Y+a9qux0CRc+z
    userKey: AgAYVKNtdj+oBdvPVtOLNs5GSeYJwyJhOCDfxxcpzeq5GUcnwNgRS7PV1gjZ+5jsvjA6wuldR4UFIP9ysVgroNAtM6T8Do3kPWZnv1Owkqb8E9/M6jYdB+twxV8qqjQa0rR2XdlSTcS7J342hSel0iHAQzoyKMX1PhjSQonLUVTe5pXRlWl3zQq3a9R4vGFbH/vo7poMT8Fa/3MretXHXcQFV9okCl+GleSUZEhWxDa7uq3aPEsfBSBoQRCYMB3Mneges+Obb4YHibsCdACUBa4XEmXzSc88h3yYAaHBMCFMbXuYpKdEzQUHW4+oWKAzLO3+JduzYSkZlpCP5qIWyQ29AmZaAxvcglFWQ+5FD7gHXlwUbsvz5SsCDupLb3yfjO4/iGnSj1Zb/gUzSjT8dGL2tY0o2LErMJ8Po55/HTItbFdVyOcwaCZA++hLe8fmqdTWQrJBhxYw0n/ZMYZmouclgNuRweeV57Y3/hHz6r7WPQLYhuQfHl6JNdjJufvI544BHWTTgO8jWvpjzreTJvRGuOFwWBM7wlbaG1ERMfaUBNOpCu6N1fbbpaqxal8fvi+haXU5Ze9vnKm2FnCsNc5OZBGLJNd6c/Iqd2YEfa/KoFteWGYq94f3sAlmeEYSzBkMzubggz7cjRL3TL/VuPlV1N2A9XWfdLP+meK1/yBb5EPIsqUvcHmvyB4ydzehrKge+GiFI0ZMnmIh5tcaa2ka4uUQo8z5BKb794dkKVYAxUXEfx/eHUz6
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
