---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgCILE46VxwL/hZ+BvTxxdcHUTgiar7QN51UhfIYxZleFiwK+4sbSB9Vhiuct4H5iD58wBOvMsXiRZ3P3KBzZrQKlVPLen5GhYSHBRdjPBiaweW++RwchJMnksH0jP95ANIaFU5h+tZ1r3raAfTzj1TVEa2Mr7bSg8iuhKcIb8mK2y7TxD1X2UH51Q4tETWqoz1mnS8nvH/Azv3FAn2NflE2z82XCjInguZN4iFaQWP/4KtHJor4ZsPgZAgoAxxBPGWt6sGNCDlOFfRDQxkGqLGRKqT3U5llAnq9cpVFf5T3Rg3CHycjc07KNJ/AsEVxWDWNgxg7Uav4eev0sB7lkdkHxzqoW5x419ya6wTUPOT4w7JQEppjmeZe78n8M9etCKp+mROwlf+W/zbE6Dlhgni6Z6L87o+S7lW6qQxffKcZYg4V6j/QaKP1CNY4dFPXyF3R/JvM25+1sKg3hguypkhO0HVOznx8BXPNugy6LU6TbvHdjtpHrLlTJAol0p8v+dpMNPQOAkG5eNxXyEZQ/IFjWsy7M3RUrA+QWWx49JCMLWeK//MxYwIhPoEpnfOoX1IPnpCWNZI7BeHN8XsKrJOX4fb9F0SEZXISa/HjPCDFfxgwvkKVPmtM14fY97ottF4p2dytEfQsqBqabv+G/SfTTGGru802kUT6ARUu3mAjuDlcikKcJeI9ehKkVwpJSBpuIvnGlPdFXd9b
    userKey: AgAqwHlKcpO309EdGf1A1ftMkVSNivTEifnvJlTXftoTwnS0X/zFE1Q7gEO53x4JtgtlJTcpIcXcSMUtl0YbrOl6xYUy4yyn24RMqgHYfK3/t0fvgXB2AV3YEoQ/0A2eKcGXP2DIa59kH/pAz4B+mfZ+gQkmxFRcEu0p5sactHPE5IDsEVV3s2kQgybt4wxiqYUonY/mBhuoBCmz1JgAf3m0K/QuRBk+OMa0Y7ukq2lbNP35on1AG8Pna1mQgIry+KFKk/3fkFsy9eOHZN2Ap2oF1jJnkLMXZ62iRm1KgH/grHM1amG9T5bIht9UK4wngj87ZL21Mh5WJQFk3JfzrhAdyBK5uuMQ8EsFonETzKgONqosa6KLa1lhh4o8JpBo0FwkOmXVVDbm52Kg2djdVyxXmw/I5tD34eURAdF51sRMV3BxXwl7CSbYsn2z4nnT9N5Ueu8KYZ5f1eNdAgSbuOyCJD5Og5NoNVwG/Um3wLMbQYsWQeehGVXjPM+NXI8s4AAm40F9hqXkBn/G97DcAmzw7PeEUCeE9EiZMGq3zYTa8c6c6oy4Go/bao/A5X9kcoFE+nJCjU9IwIg/4myfm/ZtpYTXhyf3UvwuVN9jf1kJfuE0vmrbjt0xuIA1cppo+Q2XrrI0mMdu/5/7NbQ8+qE6Wi9JUESbnfpkgw/2AeITT7eahq6T9zR3/DeOWv175NfrD5TVbGFk0rxe+FL8qmG/C1gJ1nqMsA68DSal/q1okbX9bQCMzvs/
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
