---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgAur1HEoSL/2t6JQwQVkBXcRpMjMIqKcvkKroQckQVILH6s7D6R+y8zPitOlypXOOD91+vdlvMbJ3f+Rjb3/ErpGDSZ4Wj067vaXT+joij/1HsWOnhLrdxnsumtAIGVD46vVtIV3IBee9+MMNl84R32+vggE7f3KS+G3PDUPgCbOC9zC7H6WxpyMNJTxOsJo0ciGKyvO3gHrKMPKqdErGP9c1iku32h4amTWBiZu92ILWulZtqGt5guAD1gSN2OBiSvBWnoN1JICuZU0ef2xPNSZnnBcIYDip3YRu5UIXUdjacFBIMuNZjmVzPLY6jUMLiLOcHSMTA5QKVanf/F+GIsdY+ndQoWstSJqXibwsaOdSaCPw89ls8FZe33E8e8vXT3SkEnlBwFusApqdS0taDnaAa3/zgHeGMkE95M59GTeHS5YhDCqlJoVhU/ftsO9tpsEASeL5x+GOk9R4pv3KJ5B4Ix9CMYEgzHzftu1mYoZ3y3Mww0vuAF4jUuPcjeHgqTqRxQaurwwDrn8ElbzYtpxu4XfmjjaJ2+lDx7+MBnKdA4XqYE080hN8McQBwFJglf7ZhnHlGIp+b5Zotzo7iyCFr9x3jhxmMRu+CuShaUMHSLagOSnnwbtV+8Iazu0uw/5pLueikeLmdLWljVbhaaaonyKT2h/T2+s2BkaGAfR0E/K0Jz39zmB6WBnKGcEkbaLJBNo+sbkvAI
    userKey: AgCLp3hvMlfwCW7td2Dboo3yMUW4zN4AsXuiGHd60KUmXpYVMfq//gVB+JC+lbswewshPgeeeuBvW0BnWZyjW8EbUghMV5qmDpPKLh+ny28afjt9psYT7mFBqts6EavqLJVLN9by5T42A9s2DPWQ+Vpq0SqS04FMr4YEECvnUjvSS75fUCfAA9wJOuak2LJUMgGPqihFY0F2ixoiv2XCWocZt9rAjk5o88W/dB6nqtJyD2bPfDjko0EMxw+ahu8Z8dkrHR7diimL4xLEWcc9BcmP1e6M96x8IPIdhXX/82n20e6rlCFgJ5WKi28se0cr+Obdro9mSZGpJr9jb9ts7g1g9tJtNwYBHXwQu2zEuRmeVUfgmbAFhBPM+cbTWsAnbom8T6kDikhsbbvfnjsrrp6nWIbU43V0wfnjVYx6x+8fGEPryD5V3NC7FRLQRC46zqAv3sGfA83NGv8hk2BbSHkxcUjbeiYczXJBLiRXTQDpsVi4EzZAEArR6NN44hi6x4u43v9T5Qw/T1bRB5tPcav4Q/OexkVFWVhut/UjSyT+U2+GCtxMolOfvb2/1VGuB4rwwlJ5yUl8Tdt/GthcA2xpqSq0Q8pjM2qJid0TmWDBGhteAaox0I+5mGn08OZsVd9Kuxr436Ol0ysWWcbhVb63l6cTuWc3oJvEkyaph89PotaO9npdiELIJC3HReOjoJz5CKGc2wSitqX/qLE+U+a9skpZlMWllRCQQEIsR3rKASEcl8V3b5SK
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
