---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgC2sICWUiSCupjrQxXWjJSULdJb5uGlnnwjWev5l1KjTV+XjKML2BJgJDTm+J0kpxj3WfkTIS84CNzltexKzBYrVxHt1BOiVufdJEvK2m/lnMfXo0JER8fTafciNiH/AQj4BZx993hYbpuE0vymg6MuxoXzFMZVkS2ej9ynEtR6Ew+M0KY7GLwO685O83JuSio4u8piHddmF+ilifBB7jaab1hd4OmwxEQpaJ+MC1XMFcqqQJY2x/5Tn8Acqqr/Ew+YOxB7I9r/HnuHaX3+ImXi8xT0HyfY6besD0M4OMcS6PDPj1RFJbddRrnoIEl8iOK5wi7VBol+ZNiy+FKKWpDT88P6WVADBSQnyvV2F9dbi2c20w34vqE5o2MSZA8H4Ojf195I8EckDtFSTcb6SESwVJzrqa2442mYJKUBM5XpRLDLqusABoMBACsq1Zttv0YVQQJQ7eXMWjAZWsWjSBYdsoG5Br33/CK6MDD4SIdurI7TFTs9JJm59T6lj/9W8NLdKNWKR+1BcOO74GtNrCtZ0AQvAYAQ90HaqHeGq/wZEuVbeqhOWb30mUAZvfubTpkAGnMKCEObffLTMUm1CByy1V8twSzgHUCaBokjioNYECJri0SEuwAa+0+4Kr6ZddCR5NB8Pc6fgVVgAdLDwui13CAij/aL0Il26vPlz6lGG1sTDzR76/8qUcJm3LNPOymiouOPp2LE6fho
    userKey: AgBFXPHesXFJjRlUfmfK2X36szZZY200VXnItPhrl0ANAayYchqHDRTwxBbaiiKcuxGU10voKK7SebFfe2NNqVOZGuX8eyGdr+amORKxX/G3mF1n5igoKUrWWvmoEE2UzL7uTJvMpjIfgSu0NNV50XDJNSxsOEHOssINKZ6D59p1QAhtEQAn/Cs3cMmutrB08rJaSotAkXql9ySGK4I2jhcYhhxWE8A0G/xAi8nJKKo7tWSfPlRYbPP1TQBWT+Gp4Azue6Gy2jiv92cdnllg3F2TqgHpPjYmDm6/ECIhsS7NeSnalR4adzm45YyuENwwLiSSyTYisIIgxw4THiDibiKVLOu9igOyC0zV5xDivoJfdwpvYGqKtkLGNKmwoLy+ykUfK5dhB5bnRPtlb8A+hgv8Q+2XtvnDqUULsahCIsdug6i5qjWxPfYT+9OLU+gG2Ky9CE+Av1Bclt4E3LrOccCmTRgPnKJg4fhwz18ku7285w+rSNc+Ul0m08vw3PFp4hRd7dsUobA5BHkLtxfrJcutS+S7uNvsI97MkZajxOZhji1aZnJ1j8WHS2LWBDDz1S7+EHHNPF7JsPwrNRvLMDTpRzBFzfXSzNrsw4TvQU7vZYunUsLgwqZ4GdeT/AK8gQGyl9Tozdh2G2OmaMIHVbMqtO6P+0geGvadmGMINTRl/L5utoMs9eyTD9DnJdgS2NQOoIXN5kCsO4FHsGqwCjqMu/jkemIQxIJYsZISrDsyyHWBsQCx/mB2
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
