---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgCeqmqLUeK3C2BAMuTfp6AwwMqjCSn6Sn0zNGb2KN3YeEH6r5ID4iyTogMoOqDfprcfQT9gptEQ4MX8v5OmpO+j53zVBtY9rwUAjaZVhRqgPBsJKwANqYrBVMkFFkWOzymjpM+d+tc9Yy6uJJbGjR0l0VnrVFI3SUZ2ZGyUeSiH15zGB90PW26fO2ssImKimrLWZT86qR696UBgktW/qTmoj2fm+4hTX38M++m3OKPVmokfwbpd9MOmWihxaZ27J/2ILUD9DIxgCOCq5DoKfwVdA1P1WkzK7Txc1dgeAGyaqKQT3R+85IBcobGf1bBAOQte4GeZevFL/BLMiWiHnyFRrnf2eWymHE/DidtIFuy29gE7GAhjFFdCOZkc4OvLFig+pFC8R1pqg1Ov+w7i8GKhRlhmnOyVWvmPgMp4WM2+oUeqddy7bKyCTixL4dm4o7wQvQ/qVBY09CiQ8LT3tGZmOZ4pA3lB2nM9xTyFDloEfapSqWb3q1t59qzEZbdL68lnRiP3YVev2LLuK4JkGXnjwoU5Aezrom9PEzxKbDg9qyv+Mm8ZzzOCZetMBLxpA3fZzpmnqMn/uyZ5OHKZVhY6gnXbVuRGI4MwvUrvjIJ3wj+OoTA/FAGPmKs7blLdH37oQ9aw5WYtQbsf3MKESuZ9CqXKKC6TStNgYlGbKn2EeYk+Ew6cmK9J20X+nXdvoN5lGp1eIypEQC77
    userKey: AgA0KdMhJbqdpeky2TTT6G29ttsB+mBkTQR3ePDUWxO9XEpkYR79EVFnNFsweF/eyA0lBkh7YAIqrcX4eEWxhpCxkUByBboXGJaljVHj/eraN39X+lOBYZuc6nzFGGkF3AdY+Tw0ackChIEOtttkja/zYJSV7s9S8+OJU3oQD6V8PlAxCxZEK9Gj6pdYicg2bgcLEil/yc0d26BAcDby8htmjw8ssrIBFAAaDyJ8jJY6gsvV1jSNMuQqWmp70Z4CsHqT9fOMS0CMdNUnsNpZhZlEOOTlD1QLenFkZTkfsiiIRnU3TWGT578esLCo515eWxASsnE2H7HW+VyZjBbvJTyUACrO25C4XsdlmL05+6ISG41cDYsiuGEixjQBQSymZbRF/mZ+x40sAk/uyfzGiXEcWwM0bHU3da0hzbKo7YVuX1C1/tHucKr5ubOstXUtgZVCPxY7Grm3kpXV6Cs4xK9vfx2DJE3NvW9KPuLqOx9RmPxyEWTUrZKDAEO3oPG3EGTuAU3LEHN5ozyB+IWe7pq/Ctm487ZaOxGp0eKIr21adPiZcz0aMOvc6nags6aGZfgg2HXRm78Fo9LU0sSgL4DDaE1n9IbmN2TMxWosZYoXrZeaVvh7KZ8PQFPreMBcD4M/9/zzeidpezQKSHbDSxedE1aYTdtFpleZoiU+n0JZTI8neO4VZJslI3ookcFP8wZ169Gz9lojxU2P/kEg9doJhRpbSBhxgodyPKrtEHPdWeS0PzgJiMLy
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
