---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgCCILsU1fPkPfn3Xo2KichC9658JPTmwnelPJMJAmofBDhoOMK5d9QSwbXaw/sn5BVu78GB9k2DXQYUmK8Rhiwx7bZppZ7n+hEX4NbWiD3pkuRSYZrpb8ONHi4sXRWdGS88srKGj6wLYO0r6iLHIjtnsX/b1+SgHDOPoAjMrWor0bkHr1s2COffjLcrEuPK3kw9sF8YGAg6foMxO9bg0lt/vT5EACRtbfYQ2rtF7Bn8nkvTwK5sNfFK/NBOTlTgX1wK1FS4F7yf90CCnfQg+cWVhPqzG55JArNHgfBnquQV/vZ7KLdwavmxrH5XeRdELb+bMxFxnJuUCLs6uG9UkZWo0MXnsOBN+wWxIQDgQYd7udZZdTGA0maHhJNVGstLeifYKcugy0/vwIYPU1SBmrvhpHqlHLW70DBBwzZ9FAyUEKYBVKarVMsxtstbXjzFBNaK7xWkJd8DrHEIjmUR3OysD1j/SqOl1yT/ANPbGefbyo6VzhyYhmmwAr0jnOZfVymsDX794LR9ZHTEGYQjKWDRf7gdlA9szp/dneOOjgoMppZJgRAXOfKsqg/GJx/tcIj7xUgxHM1vkoL+V4YWx8rLy1OVWfgFbcJGVC5MmzA8d9TAGsrnUX2lpRPNosjVHtDgeeBVBzAyfM5MtBpT9bDT0raWBIrJ/4iKeE+WqtZDm2oyABzPkx2kW7u7WNtyuqkk56/Fk8A9+oTn
    userKey: AgAFBnwCY7U45Ynse4lFg0o0qVjWHD2v09wQHhMpyiHNNr9rTWpGUlG0WbLSTNxgSJYnD77Q9BnUZNhir6/X/oPkzdWUvrVYXuZN9PWf5vxeiiKtufBsTJl//3nR55vTwNbaGNxYLCDGA7hrfdta57bc1C5ylULzefsjVz58w4DrTLuRoqduljZhL4OgzrbpDUbNKxNQaKHKUIzhDK/9ZCggF6AKSjwUwt/YNbs/kbOv68YjdXvlHcw2JLXmEPQX4+SJcUSXFBDLPg8wOutWWHrj/yfasF6585GPd3O59ynIfe2WaRulrpg+MVex/SC3dQxbuCcnwEUgaCgAzPedByaN0pT/xrb8dy2VuCF0twZZlVrrRkMWuWJZBTSlYzB/Q216yqaK3c/tQG8cZjGU6v4gsXEn8pajq1i30P8ykG2Di1+TPDYhJEtupBIaMY4JxmmVQeGV1BzFTEgB6AIrvWHv3sT9j1PStlPM1j5oPi62StnfbblOnWqyrbZ/mIhV1RzO7B3462GF+bCz3UPNtI41DN9z2MORVJpACX8eSjszS5owWNnN4JuCDTUP5+ph+7fd3ES1CfTgveqKPxMgNiAr9M7sHRbtwVU+VV1ZPSQfGtz9MjbQI2/Jvn7TdDU5Y7Mv8FwSnD/3lfuJvCik6Txx59LF5SYsTdpHZQ+iVxDbVwa2D11Wv3j6Tiw2wo+WYtC7cPO+E6bv45zQlw9bGUrqc805DeiAO3vhdq7kUHLe2yuiiGutyNqz
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
