---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgB3D3b1iZNtlGpAZvyjfBU8rZjaOB26OOL8Uuqcx1h0D2qBVL3scMoUuuni267Il2XsY4tIHGvh5Snd9hL2WXgvwNuAyLpaB84gfnvfJhgfOqULP7CgjOsjIU2lwpsZAD9eqi17H1pc2s+smr1K8S+tAAKMPuNSOa7BFx4pB+OAmWXto/zhrVncEeZhwuYe5IasGoVw6X8vzYE6nrA3gzO26C9aMO6iyqILNy649Ofp3vSsThcl93Pn0K0h+tg5i0gIwPdtYQTSzRJREOddWP9ufZKYHqQRC0DCpH4dH9f6UcRg8s102+IQ9//Xmpty7QaUudneNSxd6ZL8OjlJ+GA3Uaxxa+/E8i7s/wnYnHJymX9jW1JdFIuC7JtAr9+CHyUoZo+30cgTZHQpNf6YC3U9xVFkPVMksvf3T7v5mlP7Cl6qTkYJ8ckH31HOmo5fkSh7fybMZVFUR/mdSBPD2r4NJovqbP073peERoqe0u2py89chhNUQFbiyn3d4ftVtL81PAVR8NAvPG9QHT0K7YuYheaJ5lz3cNCsFVpGDn7/BB5cb5tabFU60fNB3npCijaOXAZvKpKZqS6kWFCkv+VE/nFOBzbtOmqDAVasOdbS8D9ZmOJ78s/DzVCL7vMigk26lUoSbOZ939zmnXa90/9W3NW6/ldc5bmG1NKnWtGM4XCPD0FUnASbRiX6GISRhhtdKndSeg/rrrHe
    userKey: AgAGhK8ald33mp/dbyuOhk5Q03pUrjp3/WV84P2KD2wjkrwUPhP/xwdNViJGG0xoroszYhatxQMzGVZFe5OTgzq29Gqwqc5LMI0LcYGPGx7wccuZ3o4xkI5lU7EI+xtPXPiShn7tdfbq5xmzQeT15Hcy5Vx+avwMuHmhm10jSjWG+4w4d3Yw3M8zO9pUzGjrvve7J+sCE7u0/5jpvkaU8lRwItJspySEXU7HrpmME7sVKcQwc6Gbu/BIcYZXI5PzjjI65KYeqjIOKSKdLfpLIsaz6w4VJhX2WE62Jrl9PdvjHJhk/NV0hVS221SU9MONKNFsxvM0X+iTRDX4DgV5b7piaz8ZQUURgle5uJ9630gjYW6ozttQLC9tsEjIRyOO2GcDRptTSAHGF/zVEOz7qPyM0yTCwSsuM6Hw6RBKVJxhI+KQ581EQnLiPjXb5jNiSi6kkeOEqjJGE8l1OpLBITiFgiYpG/bZXsrRKpLzN/XYO1wCuRWTdlvp+o2hdygyO0EDXIqYcNIsHTn++vQctyaatkRKXFri8mg/0WeWLPmKoJsBuVOJ6XtJG3YkN2Rrt2rvn9XApsqjwNVa/ZL7b9mg6uLr/7pQw7rCqPsl97Y/6CA7zKy1SKsRn/lLB9xsa1Q7pG8aksFga8dHELPH3BXt2ydS2Y3IxzP78okJU79zUk1qdymu9LK/CwfIq6OHCw8ilMqkUbTNn428L56fYoH2KkgOOLm1JU+pvJMFqjSk37msE5FUhJYZ
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
