---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgApJlUYOUg1lGEgLkfq46Jk3HrqFBC3IaRF8wJsDER7LN5YFqMun2bNJlRLcKOn0qjLtbbAhtfx0viKvQVkgVUGd9JCKE5h5ttSP82bFrKGepX3MLFhZ1v848Pbps0G/9WHO4Zgzb194/XeVPMhg+8OY/QBwW8nCOxfV93NBPnbmo0VxBU6/jHwJ8W1uc6HpPkC82uyormslxZZnAvWLtdG8pxjVPBEQt9Gf/8Q6kuq5wM4aXZrwiqHDLZ/CozptMrGugsJ5MvXSMybisashTuDbLjCkTSUtuEPlSUrfeuF/gZxBR6WkOF6mcz8GTiKyK/T5qQHIMUgFDfuBs3+u0F00+RnUO9vK1mVCNbEycrwyDekLhjf0G/GUKcdEPFsLNHC9/MxkfVjRmXdazKiUy+1SpRVpTiKGL+DIDI1qjg2bK8R1of+MGDpmyiUS+1DZzMjlEfPskCeU53fd5R0pcb1OrR0Ztc78nVogNugMizZoQF4ws/A7MUCjCT3N1CUfgs1L/3ZlExm4i0gWp7qgT9zkK/5PA+OdadpCR9lrxWXaiNWfXGsRMDq6Nqezu4c47iYJycWCU7vAnd35YBKWkOD91jPIhHuhdsZwuPSnv/nQXXrWuEVJR9nEULfNK/SDfPDhT7Shi3D1Tb5Xa8MlKRHja8ndwMbnARray1bxkEIX8WFG8V+w9tlGdnCnqNa6ke2i3mRYmAHsIp9
    userKey: AgB6TPg++sTgQiLiolELoVugyhhKnVwnuVrNoPPc/lI1VFcCYci7OjSJXH0dNXeJe1XB+nG9cu+0lok6pQTkFpZFwa9cENy4WG7SaJOGLFiHFMoDEYJmn4WpumEUhs/IZpe3lYlf7GngwlKAkx7ZATLzC90E4ve4Ouw8OlQ7jAHh7BEqLEhyGAtz1D7UXA3YZE9Nsz6fqMS+Dk3v1+JNmfukS7yt3KwQJrFc0VYxqwQ7fLevwkpLVi1vXlWWan0swUunP6RX+pf61oc9e96RpRpD7di6ZduMoPjdJg8pzUcLls+jtyz9bdIY8S042xwgySufb9LMKmCdJRryFJeyRLGAtggYuPRkTCigNgKmoBa4peVq1CiVwq7prchB7Yczaz9Chqzn7sKTYOTrcjCiGYTJvcb6Eu+fnuwJDUdIXI+KE+auu7DQ1SxoQ8buOZjCVNtJIskyofApwDdpLz/6m5NPwZWcyEOoNT+zufpjgD5fJsUuJ2oLgpZsr8T5cR2cNO1+lFnqVHJUlWTfkU2Br2P049KpgsQSvhlRKiVy55aH2HM6Nf1hlWQbsp5aF4qw0uDMdTWjWxz4R+oOoikz2q01rxQJKvgrDpo2QXY70+YRXfGlrizx+E1RVO8l9Ntb/nykMPCX93WwLdrnbIZYFvzX2CYtKPJRmzXUkmSosEmnFftKha6Lb5ZXnEpv7nM8gQMmL6QV1yv4Mq8ljPF3edoze6tD6rEKPPhZgV4nZyPbqNJ1hFXLR0VM
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
