ceph-csi-rbd:
  csiConfig:
    - clusterID: "7ee1b4fa-1bef-4908-8848-9895fdfd3cf6"
      monitors:
        - "grace.labs.ahinh.me:6789"
        - "shizuru.labs.ahinh.me:6789"
        - "nia.labs.ahinh.me:6789"
  storageClass:
    create: true
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    clusterID: "7ee1b4fa-1bef-4908-8848-9895fdfd3cf6"
    pool: kubernetes01
    mountOptions:
      - discard