ceph-csi-rbd:
  csiConfig:
    - clusterID: "7ee1b4fa-1bef-4908-8848-9895fdfd3cf6"
      monitors:
        - "10.1.1.3:6789"
        - "10.1.1.8:6789"
        - "10.1.1.5:6789"
  storageClass:
    create: true
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    clusterID: "7ee1b4fa-1bef-4908-8848-9895fdfd3cf6"
    pool: kubernetes01
    mountOptions:
      - discard