ceph-csi-rbd:
  csiConfig:
    - clusterID: "0a18b03d-b8a8-4f82-babd-7df7de66fb9b"
      monitors:
        - "10.1.1.3:3300"
        - "10.1.1.8:3300"
        - "10.1.1.5:3300"
  storageClass:
    create: true
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    clusterID: "0a18b03d-b8a8-4f82-babd-7df7de66fb9b"
    pool: kubernetes
    mountOptions:
      - discard
      
custom:
  enableSnapshotClass: true