# Harbor PostgresQL database

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: harbor-postgresql
  namespace: harbor
spec:
  teamId: "harbor"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    postgres:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    harbor: postgres  # dbname: owner
  postgresql:
    version: "14"